--- 
ApplicationStart: 
  - 
    location: ./start.sh
    runas: roott
    timeout: 1800
BeforeInstall: 
  - 
    location: ./install.sh
    runas: ec2-user
    timeout: 1600
files: 
  - 
    destination: /home/ec2-user/myapp
    source: /
os: linux
permissions: 
  - 
    acls: 
      - "d:u::rwx"
      - "d:g::rwx"
      - "d:o::rwx"
    group: ec2-user
    mode: 777
    object: /home/ec2-user/myapp
    owner: ec2-user
    pattern: "**"
    type: 
      - directory
      - file
version: 0.0
