--- 
artifacts: 
  files: 
    - output_artifacts
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "node server.js &"
  install: 
    commands: 
      - "echo \"installing node packages\""
      - "npm install"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo \"in post build environment\""
      - "echo gulp"
  pre_build: 
    commands: 
      - "echo Nothing to do in the pre_build phase..."
version: 0.1
